In [16]:
import pandas as pd
import numpy as np
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

sia = SentimentIntensityAnalyzer()

In [23]:
%pip install nltk

Collecting nltk
  Using cached nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\aditya\computer science\machine learning\mlops\practice-project\venv\lib\site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in c:\aditya\computer science\machine learning\mlops\practice-project\venv\lib\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Using cached regex-2026.6.28-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Using cached tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\aditya\computer science\machine learning\mlops\practice-project\venv\lib\site-packages (from click->nltk) (0.4.6)
Using cached nltk-3.9.4-py3-none-any.whl (1.6 MB)
Using cached regex-2026.6.28-cp311-cp311-win_amd64.whl (277 kB)
Using cached tqdm-4.68.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, nltk
Successfully installed nltk-3.9.4 regex-2026.6.28 tqdm-4.68.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
df = pd.read_csv('../data/cleaned_comments.csv')

In [3]:
df.head()

,kind,etag,id,snippet.channelId,snippet.videoId,snippet.topLevelComment.kind,snippet.topLevelComment.etag,snippet.topLevelComment.id,snippet.topLevelComment.snippet.channelId,snippet.topLevelComment.snippet.videoId,...,snippet.topLevelComment.snippet.authorChannelUrl,snippet.topLevelComment.snippet.authorChannelId.value,snippet.topLevelComment.snippet.canRate,snippet.topLevelComment.snippet.viewerRating,snippet.topLevelComment.snippet.likeCount,snippet.topLevelComment.snippet.publishedAt,snippet.topLevelComment.snippet.updatedAt,snippet.canReply,snippet.totalReplyCount,snippet.isPublic
0,youtube#commentThread,WnhsayRvteIV6KBpeO2l0RLsF58,UgwD64UPiU2A9hyw8BN4AaABAg,UC-lHJZR3Gqxm24_Vd_AJ5Yw,iRRpvuMG7AM,youtube#comment,hdRncGQTvTFP-_VT19BnnKWrDaA,UgwD64UPiU2A9hyw8BN4AaABAg,UC-lHJZR3Gqxm24_Vd_AJ5Yw,iRRpvuMG7AM,...,http://www.youtube.com/@LTAnisangre,UCJDiQksN_FLydDXq6TssDRQ,True,none,0,2026-06-30T04:52:18Z,2026-06-30T04:52:18Z,True,0,True
1,youtube#commentThread,lj5ORhhyMy4V8EevrNAaX8GMPuI,UgxLDOTLqsr55AO8Uk14AaABAg,UC-lHJZR3Gqxm24_Vd_AJ5Yw,iRRpvuMG7AM,youtube#comment,ZCYVOoq9Fkojw68-RuaRvcSYuNM,UgxLDOTLqsr55AO8Uk14AaABAg,UC-lHJZR3Gqxm24_Vd_AJ5Yw,iRRpvuMG7AM,...,http://www.youtube.com/@workwork3240,UCrlRJLJS4keEaWmk-Y-4tVg,True,none,0,2026-06-30T04:51:16Z,2026-06-30T04:51:16Z,True,0,True
2,youtube#commentThread,Pyke2TsrgyaJn2JAQNtJ_XgqCvE,UgzonbWj6BsRvDRaO_Z4AaABAg,UC-lHJZR3Gqxm24_Vd_AJ5Yw,iRRpvuMG7AM,youtube#comment,BsNF0YzSGlmlE2NU_c-yig0unYI,UgzonbWj6BsRvDRaO_Z4AaABAg,UC-lHJZR3Gqxm24_Vd_AJ5Yw,iRRpvuMG7AM,...,http://www.youtube.com/@Plantmotheroffall,UCq87moEDxbIkDs4QUgJHmFg,True,none,0,2026-06-30T04:17:00Z,2026-06-30T04:17:00Z,True,0,True
3,youtube#commentThread,mvrUn628LDCitZN1GdNDz-JyiP4,UgwJVya7UPeN4zrjM2p4AaABAg,UC-lHJZR3Gqxm24_Vd_AJ5Yw,iRRpvuMG7AM,youtube#comment,8lSvipowVqr4suq1QK5n3G05RBs,UgwJVya7UPeN4zrjM2p4AaABAg,UC-lHJZR3Gqxm24_Vd_AJ5Yw,iRRpvuMG7AM,...,http://www.youtube.com/@Ki05596,UCmDDV2OpAb2C09AeFp_mk1w,True,none,0,2026-06-30T04:00:32Z,2026-06-30T04:00:32Z,True,0,True
4,youtube#commentThread,HfEF-IGvhk0MY3OfUI2jf0uA9ds,Ugx3RIabmhVXdxCDMLZ4AaABAg,UC-lHJZR3Gqxm24_Vd_AJ5Yw,iRRpvuMG7AM,youtube#comment,8ouqLca70CDkOB7NBf4atuZe0Js,Ugx3RIabmhVXdxCDMLZ4AaABAg,UC-lHJZR3Gqxm24_Vd_AJ5Yw,iRRpvuMG7AM,...,http://www.youtube.com/@bbl_gm,UC7Kx8f8akuNdDfV4F9d6Fzw,True,none,0,2026-06-30T03:10:23Z,2026-06-30T03:10:23Z,True,0,True

In [4]:
df_features = df[['snippet.topLevelComment.snippet.textOriginal', 'snippet.topLevelComment.snippet.likeCount', 'snippet.topLevelComment.id']]

In [5]:
df_features.head()

,snippet.topLevelComment.snippet.textOriginal,snippet.topLevelComment.snippet.likeCount,snippet.topLevelComment.id
0,I remember finishing my first I went back so m...,0,UgwD64UPiU2A9hyw8BN4AaABAg
1,Next video I turned my manga to an anime,0,UgxLDOTLqsr55AO8Uk14AaABAg
2,Ngl i missed seeing his gameplay Would love to...,0,UgzonbWj6BsRvDRaO_Z4AaABAg
3,Thank you for always being such an awesome ins...,0,UgwJVya7UPeN4zrjM2p4AaABAg
4,guys he draws a bit better than me i need him ...,0,Ugx3RIabmhVXdxCDMLZ4AaABAg

In [6]:
df_features.head()

,snippet.topLevelComment.snippet.textOriginal,snippet.topLevelComment.snippet.likeCount,snippet.topLevelComment.id
0,I remember finishing my first I went back so m...,0,UgwD64UPiU2A9hyw8BN4AaABAg
1,Next video I turned my manga to an anime,0,UgxLDOTLqsr55AO8Uk14AaABAg
2,Ngl i missed seeing his gameplay Would love to...,0,UgzonbWj6BsRvDRaO_Z4AaABAg
3,Thank you for always being such an awesome ins...,0,UgwJVya7UPeN4zrjM2p4AaABAg
4,guys he draws a bit better than me i need him ...,0,Ugx3RIabmhVXdxCDMLZ4AaABAg

In [7]:
df_final = pd.DataFrame(df_features)

In [8]:
df_final

,snippet.topLevelComment.snippet.textOriginal,snippet.topLevelComment.snippet.likeCount,snippet.topLevelComment.id
0,I remember finishing my first I went back so m...,0,UgwD64UPiU2A9hyw8BN4AaABAg
1,Next video I turned my manga to an anime,0,UgxLDOTLqsr55AO8Uk14AaABAg
2,Ngl i missed seeing his gameplay Would love to...,0,UgzonbWj6BsRvDRaO_Z4AaABAg
3,Thank you for always being such an awesome ins...,0,UgwJVya7UPeN4zrjM2p4AaABAg
4,guys he draws a bit better than me i need him ...,0,Ugx3RIabmhVXdxCDMLZ4AaABAg
...,...,...,...
72,Father time aint it,0,Ugxclbxx12oMKu0zZUd4AaABAg
73,twin please illustrate shounen ai,0,UgxJSmX9b1BMXP74xSB4AaABAg
74,Blame as the manga bible is right Such a great...,0,UgzkvDOATW7pSrwTynt4AaABAg
75,Youre not gonna be good at a thing by not doin...,0,UgxyuOZFkBB22PWK8Wt4AaABAg
76,The kitten got me,0,Ugwfk2D1k6nY4Wz6zRp4AaABAg

In [9]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\kanak\AppData\Roaming\nltk_data...

True

In [10]:
df_final.rename(columns={
    'snippet.topLevelComment.snippet.textOriginal': 'text',
    'snippet.topLevelComment.snippet.likeCount': 'likes',
    'snippet.topLevelComment.id': 'comment_id'
}, inplace=True)
df_final.head()

,text,likes,comment_id
0,I remember finishing my first I went back so m...,0,UgwD64UPiU2A9hyw8BN4AaABAg
1,Next video I turned my manga to an anime,0,UgxLDOTLqsr55AO8Uk14AaABAg
2,Ngl i missed seeing his gameplay Would love to...,0,UgzonbWj6BsRvDRaO_Z4AaABAg
3,Thank you for always being such an awesome ins...,0,UgwJVya7UPeN4zrjM2p4AaABAg
4,guys he draws a bit better than me i need him ...,0,Ugx3RIabmhVXdxCDMLZ4AaABAg

In [13]:
def get_vader_sentiment(text):
    if pd.isna(text) or str(text).strip() == "":
        return 'neutral'
    
    # Get scores dict: {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
    scores = sia.polarity_scores(str(text))
    compound = scores['compound']
    
    if compound >= 0.05:
        return 'positive'
    elif compound <= -0.05:
        return 'negative'
    else:
        return 'neutral'

In [17]:
df_final['sentiment'] = df_final['text'].apply(get_vader_sentiment)

In [18]:
print(df_final['sentiment'].value_counts())

sentiment
positive    47
neutral     18
negative    12
Name: count, dtype: int64

In [19]:
df_final.head()

,text,likes,comment_id,sentiment
0,I remember finishing my first I went back so m...,0,UgwD64UPiU2A9hyw8BN4AaABAg,negative
1,Next video I turned my manga to an anime,0,UgxLDOTLqsr55AO8Uk14AaABAg,neutral
2,Ngl i missed seeing his gameplay Would love to...,0,UgzonbWj6BsRvDRaO_Z4AaABAg,positive
3,Thank you for always being such an awesome ins...,0,UgwJVya7UPeN4zrjM2p4AaABAg,positive
4,guys he draws a bit better than me i need him ...,0,Ugx3RIabmhVXdxCDMLZ4AaABAg,positive

In [20]:
df_final = df_final[['text', 'sentiment']]

In [21]:
df_final.head()

                                                text sentiment
0  I remember finishing my first I went back so m...  negative
1           Next video I turned my manga to an anime   neutral
2  Ngl i missed seeing his gameplay Would love to...  positive
3  Thank you for always being such an awesome ins...  positive
4  guys he draws a bit better than me i need him ...  positive